name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn clean install -DskipTests # Build your Spring Boot app
    - name: Start Docker Compose services
      run: docker compose up -d --build # Build and start containers
    # - name: Wait for MySQL to be ready
    # - uses: actions/checkout@v3
    # - name: Build the Docker images 
    #   working-directory: .
    #   run: docker compose up --build
